# Generated by Django 5.2 on 2025-04-22 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ap",
            fields=[
                ("id_ap", models.AutoField(primary_key=True, serialize=False)),
                (
                    "montant_ap",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=65, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ap",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthtokenToken",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField()),
            ],
            options={
                "db_table": "authtoken_token",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chefprojet",
            fields=[
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        db_column="id_utilisateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chefprojet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Directeur",
            fields=[
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        db_column="id_utilisateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "directeur",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id_document", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=30)),
                ("date_ajout", models.DateField()),
                ("description", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "document",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        db_column="id_utilisateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EtatDavancementDeprojet",
            fields=[
                ("id_etat", models.AutoField(primary_key=True, serialize=False)),
                ("type_etat", models.CharField(max_length=15)),
                ("date_prevu", models.DateField(blank=True, null=True)),
                ("date_realiser", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "etat_davancement_deprojet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                ("id_facture", models.AutoField(primary_key=True, serialize=False)),
                ("numero_facture", models.IntegerField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("date_facturation", models.DateField(blank=True, null=True)),
                ("date_reception", models.DateField(blank=True, null=True)),
                (
                    "brut_ht",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=65, null=True
                    ),
                ),
                (
                    "montant_net_ht",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=65, null=True
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=65, null=True
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=65, null=True
                    ),
                ),
                ("date_ordre_virement", models.DateField(blank=True, null=True)),
                ("numero_ordre_virement", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "facture",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Financier",
            fields=[
                ("etat_financier", models.CharField(max_length=50)),
                (
                    "id_utilisateur",
                    models.OneToOneField(
                        db_column="id_utilisateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id_fournisseur", models.AutoField(primary_key=True, serialize=False)),
                (
                    "non_fournisseur",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "prenom_fournisseur",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "fournisseur",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id_incident", models.AutoField(primary_key=True, serialize=False)),
                ("description_incident", models.CharField(max_length=2000)),
                ("date_incident", models.DateField()),
                (
                    "lieu_incident",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("signale_par", models.CharField(blank=True, max_length=50, null=True)),
                ("lheure_incident", models.TimeField(blank=True, null=True)),
                (
                    "type_incident",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "incident",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaitreDoeuve",
            fields=[
                ("id_md", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fournisseur",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "prenom_fournisseur",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "maitre_doeuve",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaitreOuvrage",
            fields=[
                ("id_mo", models.AutoField(primary_key=True, serialize=False)),
                ("description_mo", models.CharField(max_length=30)),
                ("nom_mo", models.CharField(blank=True, max_length=30, null=True)),
                ("type_mo", models.CharField(blank=True, max_length=30, null=True)),
                ("adress_mo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email_mo",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "tel_mo",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "maitre_ouvrage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SuivieSousProjet",
            fields=[
                (
                    "id_suivie_sous_projet",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description_suivie_sousprojet", models.CharField(max_length=100)),
                ("date_prevu", models.DateField(blank=True, null=True)),
                ("date_realiser", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "suivie_sous_projet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Wilayas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_wilaya", models.IntegerField(unique=True)),
                ("nom_wilaya", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "wilayas",
                "managed": False,
            },
        ),
    ]
