# Generated by Django 3.2 on 2025-04-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role_de_utilisateur', models.CharField(max_length=50)),
                ('numero_de_tel', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id_budget', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id_commission', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commission', models.CharField(max_length=30)),
                ('description_commission', models.CharField(max_length=30)),
                ('date_commission', models.DateField()),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('type_commission', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devises',
            fields=[
                ('code_devise', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom_devise', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'devises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('nom_document', models.CharField(max_length=30)),
                ('type_document', models.CharField(max_length=30)),
                ('date_ajout', models.DateField()),
                ('rapport', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=30)),
                ('adresse_entreprise', models.CharField(max_length=30)),
                ('numer_tel_entreprise', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entreprise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtatDavancementDeprojet',
            fields=[
                ('id_etat', models.AutoField(primary_key=True, serialize=False)),
                ('type_etat', models.CharField(max_length=15)),
                ('modifie_par', models.CharField(blank=True, max_length=255, null=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('date_changement', models.DateTimeField()),
            ],
            options={
                'db_table': 'etat_davancement_deprojet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('description_incident', models.CharField(max_length=2000)),
                ('date_incident', models.DateField()),
            ],
            options={
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaitreOuvrage',
            fields=[
                ('id_mo', models.AutoField(primary_key=True, serialize=False)),
                ('description_mo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'maitre_ouvrage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id_marche', models.AutoField(primary_key=True, serialize=False)),
                ('nom_marche', models.CharField(max_length=30)),
                ('date_marche', models.DateField()),
                ('description_marche', models.CharField(max_length=100)),
                ('numero_marche', models.IntegerField()),
                ('numero_appel_dof', models.IntegerField()),
                ('visa_cme', models.CharField(max_length=30)),
                ('date_visa_cme', models.DateField(blank=True, null=True)),
                ('date_t0', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marche',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(max_length=30)),
                ('description_de_projet', models.CharField(max_length=30)),
                ('date_debut_de_projet', models.DateField()),
                ('date_fin_de_projet', models.DateField()),
                ('statut', models.CharField(max_length=30)),
                ('wilaya', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'projet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('date_reunion', models.DateField(blank=True, null=True)),
                ('id_utilisateur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reunion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SousProjet',
            fields=[
                ('id_sous_projet', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sous_projet', models.CharField(max_length=30)),
                ('date_debut_sousprojet', models.DateField()),
                ('date_finsousprojet', models.DateField()),
                ('statut_sous_projet', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sous_projet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuivieIncident',
            fields=[
                ('id_suivie_incident', models.AutoField(primary_key=True, serialize=False)),
                ('description_suivie_incident', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'suivie_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuivieSousProjet',
            fields=[
                ('id_suivie_sous_projet', models.AutoField(primary_key=True, serialize=False)),
                ('description_suivie_sousprojet', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'suivie_sous_projet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('etat_administrateur', models.CharField(db_column='etat_Administrateur', max_length=50)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chefprojet',
            fields=[
                ('etat_chefprojet', models.CharField(db_column='etat_ChefProjet', max_length=50)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'chefprojet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('etat_directeur', models.CharField(db_column='etat_Directeur', max_length=50)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'directeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('etat_employe', models.CharField(db_column='etat_Employe', max_length=50)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'fournisseur',
                'managed': False,
            },
        ),
    ]
